dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
language: php
php:
- 5.6
- 7.1
- 7.2
env:
  global:
  - CORE_BRANCH=stable15
  - APP_NAME=ocr
  matrix:
  - DB=sqlite
branches:
  only:
  - master
before_install:
- wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
- ". ./before_install.sh $APP_NAME $CORE_BRANCH $DB"
- nvm install 12
- nvm use 12
- cd ../server
- "./occ check"
- "./occ status"
- "./occ app:list"
- "./occ app:enable $APP_NAME"
- "./occ app:list"
- cd apps/$APP_NAME/
script:
- sh -c "if [ '$CODECHECK' = '1' ]; then find . -name \*.php -exec php -l \"{}\" \;; fi"
- cd ../../
- sh -c "if [ '$CODECHECK' = '1' ]; then ./occ app:check-code $APP_NAME -c private -c strong-comparison; fi"
- sh -c "if [ '$CODECHECK' = '2' ]; then ./occ app:check-code $APP_NAME -c deprecation; fi"
- cd apps/$APP_NAME/
- cd tests/Unit
- sh -c "if [ '$INTEGRATION' != '1' -a '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' -a '$RELEASE' != '1' ]; then phpunit --configuration phpunit.xml; fi"
- cd ../..
- cd js
- sh -c "if [ '$JSTESTS' = '1' ]; then npm install; fi"
- sh -c "if [ '$JSTESTS' = '1' ]; then npm run lint && npm run test && npm run build; fi"
- cd ..
- cd tests/Unit
- sh -c "if [ '$COVERAGE' = '1' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
- sh -c "if [ '$COVERAGE' = '1' ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi"
- cd ../..
matrix:
  include:
  - php: 7.1
    env: DB=mysql
  - php: 7.1
    env: DB=pgsql
  - php: 7.1
    env: DB=mysql;CODECHECK=1
  - php: 7.1
    env: DB=mysql;CODECHECK=2
  - php: 7.1
    env: DB=mysql;INTEGRATION=1
  - php: 7.1
    env: DB=mysql;JSTESTS=1
  - php: 7.1
    env: DB=mysql;COVERAGE=1
  - php: 7.1
    env: DB=mysql;RELEASE=1
  allow_failures:
  - env: DB=mysql;CODECHECK=2
fast_finish: true
before_deploy:
- git config --local user.name "janis91"
- git config --local user.email "janiskoehr@icloud.com"
- node ci/gitTag.js
- sh ci/build_release.sh
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: rblLFytrl6G18z7H7f3cQcgJHYU6Hk7rrSpzlG0gMFfsWfgUKhHrj5no7/nO9rciK6TKlaj20mXK512oaZRIou9uj+hN4yVZA6bUsaQU4jL51JB/KHi5BMH7x6rU7lG2YbAk2LhGd1jIUcn9NB0KWB8fnfFKdCuGPSL/ebB8EwKYNgNuc/T3Wo1e75AnZRd8wzybGMlnpGnjoWLpqhOYRgEm4463vrBBszPLFY9Nd4Fvhv6R1P8clsEC3EwJRhSlOQztEUk0EnNRW1dSJqPMJMI+N8CuN0YBzbmpfpSgYUSJanPiB/lz8Q6Suc8EIwoAid7QIrwrnHEdYeBKLl0izjs3P/orwzkoRGilbYnH9ZgSo0ws7q12e8VArUzcs+M+B1dBm9Q3nePEGcmYm8nkYsU/dSlaEz0AMJatTClKP9329lGZRy3e9rHdZUBZZChm7qHDQZDG7HP4VRMH2pSHQQYl8jDH/G1me0RvqDeTPB2EIx/dJUtpbEEB5Ips55slX1HX1Va/UMpphM3YwabAd3VXG+NHHOeqjWc3zu+WWzMP0m8soVnqX1iuwJOE14mm5uPpEjV/863Ai4If37NLd5qs47ZIkzqe7hWnnClzdwkLShYh0ZxOO+VixdZjqyVE+fsoc6RnUCLatcNIzltCzEIFjGDGMidLz0gySilOD1M=
  file: ocr.tar.gz
  on:
    repo: janis91/ocr
    branch: master
    condition: $RELEASE = 1
