dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - tesseract-ocr
    - tesseract-ocr-deu
language: php
php:
  - 5.6
  - 7

env:
  global:
    - CORE_BRANCH=stable10
    - APP_NAME=ocr
  matrix:
    - DB=sqlite

branches:
  only:
    - master
    - /^stable\d+(\.\d+)?$/

before_install:
  - sudo touch /usr/bin/ocrmypdf
  - sudo chmod +x /usr/bin/ocrmypdf
  - wget https://raw.githubusercontent.com/janis91/ocr/master/travis_ci/before_install.sh
  - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB

  # Add some output debugging information
  - cd ../server
  - ./occ check
  - ./occ status
  - ./occ app:list
  - ./occ app:enable $APP_NAME
  - ./occ app:list

script:
  - cd apps/$APP_NAME/

  # Test the app
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' = '1' ]; then find . -name \*.php -exec php -l \"{}\" \;; fi"
  - cd ../../
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' = '1' ]; then ./occ app:check-code $APP_NAME -c private -c strong-comparison; fi"
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' = '2' ]; then ./occ app:check-code $APP_NAME -c deprecation; fi"
  - cd apps/$APP_NAME/

  # Run unit and integration tests from test directory
  - cd tests/

  # Run phpunit unit tests
  - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then phpunit --configuration phpunit.xml; fi"

  # Run phpunit integration tests
# - sh -c "if [ '$JSTESTS' != '1' -a '$CODECHECK' != '1' -a '$CODECHECK' != '2' ]; then phpunit --configuration phpunit.integration.xml; fi"

  # Create coverage report
  - sh -c "if [ '$RUNONCE' = '1' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ '$RUNONCE' = '1' ]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml; fi"
  - cd ../
  # Run Javascript unit tests
#  - cd js/
#  - sh -c "if [ '$JSTESTS' = '1' ]; then npm install --deps; node_modules/karma/bin/karma start karma.config.js --single-run; fi"
#  - cd ../../

matrix:
  include:
    - php: 5.6
      env: DB=pgsql;RUNONCE=1
    - php: 5.6
      env: DB=mysql
    - php: 5.6
      env: DB=mysql;CODECHECK=1
    - php: 5.6
      env: DB=mysql;CODECHECK=2
  allow_failures:
    - env: DB=mysql;CODECHECK=2
fast_finish: true
